### PR TITLE
adding support for node

### PR DESCRIPTION
**Pull request by berrisfordjohn**
adding support for node and volume and pack js file

### CODE REVIEW

**Comment by epeisach** [comment]
I think we can do better than a get_top_source_path. TOP_SOURCE_PATH is left over from svn days. 

Perhaps - changing the name from a function to get_top_source_path - we should name it for what it is top_web_xxxx....  Old site-config variable - but use a function name that makes more sense.  Someday later - we can change the site-config variable (along with wwpdb.apps.site-admin which is the only user)

**Comment by berrisfordjohn** [comment]
yes, i'll make that change

**Comment by berrisfordjohn** [comment]
I've updated utils.config so it contains the ProjectVersion method itself. 
This is used by depUI and WFM (both import it from here in branches 6908).
I've updated site-admin so it uses this ProjectVersion (branch 6908)

**Comment by epeisach** [comment]
Please fix pylint error

************* Module wwpdb.utils.config.ProjectVersionInfo
wwpdb/utils/config/ProjectVersionInfo.py:54:12: W1201: Use lazy % formatting in logging functions (logging-not-lazy)

**Comment by berrisfordjohn** [comment]
took me a while to spot the issue. lint now runs correctly - very useful check!!!

**Comment by epeisach** [comment]
Looks good.  Picked up

**Pull request merged**
